### PR TITLE
Only require QtTest library when building tests.

### PR DESCRIPTION
**Pull request by dflogeras**
Hi, looking at making packages for Gentoo, and this would help with the ebuild.

### CODE REVIEW

**Comment by DamirPorobic** [comment]
Indeed a valid change.

**Comment by DamirPorobic** [comment]
Email is here correct?

**Comment by dflogeras** [comment]
Yep, correct.  Thanks for the merges!

**Comment by DamirPorobic** [comment]
I have tagged this one with 0.1.2 and changed the dependnecy in kimageannotator.

**Pull request merged**
